# Generated by Django 5.1.4 on 2025-01-20 18:18

from django.db import migrations


from django.db import migrations


def add_default_categories(apps, schema_editor):
    Category = apps.get_model('trainer', 'Category')
    # Создаем категории, если их нет
    default_categories = ["Fitness", "Yoga", "Nutrition", "Strength", "Cardio"]
    for category_name in default_categories:
        if not Category.objects.filter(name=category_name).exists():
            Category.objects.create(name=category_name)


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]

