# Generated by Django 5.1.4 on 2025-01-20 19:01
from django.contrib.auth.models import Group
from django.db import migrations


def create_groups(apps, schema_editor):
    group_1, created = Group.objects.get_or_create(name="User")
    group_2, created = Group.objects.get_or_create(name="Trainer")


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_auto_add_def_categories'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
